Ok Encuesta
Juego de 7x7
Si falla aparece Cero
Si acierta aparece Uno
Inicar con lista (Posible problema por el cache)
3 barcos de 2 puestos
2 barcos de 3 puestos
1 barco de 4 puestos
Cada jugador debe elegir posición de barco a partir de un punto y luego la dirección de su extensión N S E O
Solicitar acomodar el barco de 4 puestos primero
Cada jugador tiene 2 tableros, uno el de la ubicación de barcos y otro para atacar
Evaluar el hundimiento de los barcos
Evaluar el ganador cuando ya no hayan barcos

Buscaminas
Cantidad de minimas con %
Poscionar por random


In [3]:
import numpy as np

In [21]:
# Crear tablas
Eval=[1,0] # Para evitar posición 1 y 0 durante un ataque
t=int(input("How width do you want to be your game board 3,4,5,6 or 7\n"))
TabP1=np.zeros((t,t), dtype=int) # Tabla para posicionar buques del Jugador 1
TabP2=np.zeros((t,t), dtype=int) # Tabla para posicionar buques del Jugador 2
TabA1=np.arange(2,t*t+2,1) # Tabla de posiciones de ataque del Jugador 1
TabA1=TabA1.reshape((t,t)) # Darle la forma al tablero
TabA2=np.arange(2,t*t+2,1) # Tabla de posiciones de ataque del Jugador 2
TabA2=TabA2.reshape((t,t)) # Darle la forma al tablero
Bu=[]
if t==7:
    Bu=[4,3,3,2,2,2]
elif t==6:
    Bu=[4,3,3,2,2]
elif t==5:
    Bu=[4,3,2,2]
elif t==4:
    Bu=[4,3,2]
elif t==3:
    Bu=[3,2]
else:
    print("Try again")
print("Your ships ranges will be: ",Bu)
P1=input("Player 1, Please type your name\n").capitalize()
P2=input("Player 2, Please type your name\n").capitalize()

How width do you want to be your game board 3,4,5,6 or 7
4
Your ships ranges will be:  [4, 3, 2]
Player 1, Please type your name
tao
Player 2, Please type your name
lilly


In [22]:
# Posiscionar barcos del Jugador 1
print(TabA1[::])
TabT1=TabA1[:].copy()
for t in Bu:
    print(f"\n{P1}, Please place your ship range {t}th")
    while True:
        try:
            po=int(input("Wich Position will you want to place your ship\nRemember 0 an 1 are not avaiable: "))
            cord=np.where(TabA1==po)
            int(cord[0]) # Evaluar que la posición exista
            d=input("Which direction want to extend your ship\nN: North(↑)\nS: South(↓)\nE: East(→)\nW: West(←)\n").upper()
    # HACIA LA Abajo SUR
            if d=="S":
                if int(cord[0]+t-1)>6: # Hacia el Sur, Abajo
                    print("Will be out of board\nTry again")
                    print(TabT1[::])
                else:
                    Val=TabP1[int(cord[0]):int(cord[0])+t,int(cord[1]):int(cord[1])+1]
                    #print("valores",Val)
                    Val=Val==0
                    #print("Booleano",Val)
                    if np.all(Val)==True:
                        print("Position is saved")
                        TabP1[int(cord[0]):int(cord[0])+t,int(cord[1]):int(cord[1])+1]=1
                        #print(TabP1)
                        TabT1[int(cord[0]):int(cord[0])+t,int(cord[1]):int(cord[1])+1]=1
                        print(TabT1[::])
                        break
                    else:
                        print("One or more positions are been used with other ship\nTry again")
    # HACIA LA IZQUIERDA OESTE
            elif d=="W":
                if int(cord[1]-t+1)<0: # izquierda
                    print("Will be out of board\nTry again")
                    print(TabT1[::])
                else:
                    Val=TabP1[int(cord[0]):int(cord[0])+1,int(cord[1])-t+1:int(cord[1])+1]
                    #print("valores",Val)
                    Val=Val==0
                    #print("Booleano",Val)
                    if np.all(Val)==True:
                        print("Position is saved")
                        TabP1[int(cord[0]):int(cord[0])+1,int(cord[1])-t+1:int(cord[1])+1]=1
                        #print(TabP1)
                        TabT1[int(cord[0]):int(cord[0])+1,int(cord[1])-t+1:int(cord[1])+1]=1
                        print(TabT1[::])
                        break
                    else:
                        print("One or more positions are been used with other ship\nTry again")
    # HACIA LA DERECHA ESTE
            elif d=="E":
                if int(cord[1]+t-1)>6: # Derecha
                    print("Will be out of board\nTry again")
                    print(TabT1[::])
                else:
                    Val=TabP1[int(cord[0]):int(cord[0])+1,int(cord[1]):int(cord[1])+t]
                    #print("valores",Val)
                    Val=Val==0
                    #print("Booleano",Val)
                    if np.all(Val)==True:
                        print("Position is saved")
                        TabP1[int(cord[0]):int(cord[0])+1,int(cord[1]):int(cord[1])+t]=1
                        #print(TabP1)
                        TabT1[int(cord[0]):int(cord[0])+1,int(cord[1]):int(cord[1])+t]=1
                        print(TabT1[::])
                        break
                    else:
                        print("One or more positions are been used with other ship\nTry again")
    # HACIA LA ARRIBA NORTE
            elif d=="N":
                if int(cord[0]-t+1)<0: # Arriba
                    print("Will be out of board\nTry again")
                    print(TabT1[::])
                else:
                    Val=TabP1[int(cord[0]-t+1):int(cord[0])+1,int(cord[1]):int(cord[1])+1]
                    #print("valores",Val)
                    Val=Val==0
                    #print("Booleano",Val)
                    if np.all(Val)==True:
                        print("Position is saved")        
                        TabP1[int(cord[0]-t+1):int(cord[0])+1,int(cord[1]):int(cord[1])+1]=1
                        #print(TabP1)
                        TabT1[int(cord[0]-t+1):int(cord[0])+1,int(cord[1]):int(cord[1])+1]=1
                        print(TabT1[::])
                        break
                    else:
                        print("One or more positions are been used with other ship\nTry again")
            else:
                print("Which direction want to extend your ship\nN: North(↑)\nS: South(↓)\nE: East(→)\nW: West(←)\n")

        except TypeError:
            print("Remeber to choose a number from the board\n#1 are positions you are using already\nTry again")
            print(TabT1[::])
        except ValueError:
            print("Letters and symbols are not allowed\n#1 are positions you are using already\nTry again")
            print(TabT1[::])
        except Exception as ex: # Si no puede, entonces haga, un "Exception" es cualquier error que salga
            print(f"An another error ocurred {type(ex)}{ex}")

print("------------//------------//------------")
print(f"{P1} los #1 son las posiciones de tus barcos\n{TabP1[::]}")


# Posiscionar barcos del Jugador 2
print(TabA2[::])
TabT2=TabA2[:].copy()
for t in Bu:
    print(f"\n{P2}, Please place your ship range {t}th")
    while True:
        try:
            po=int(input("Wich Position will you want to place your ship\nRemember 0 an 1 are not avaiable: "))
            cord=np.where(TabA2==po)
            int(cord[0]) # Evaluar que la posición exista
            d=input("Which direction want to extend your ship\nN: North(↑)\nS: South(↓)\nE: East(→)\nW: West(←)\n").upper()
    # HACIA LA Abajo SUR
            if d=="S":
                if int(cord[0]+t-1)>6: # Hacia el Sur, Abajo
                    print("Will be out of board\nTry again")
                    print(TabT2[::])
                else:
                    Val=TabP2[int(cord[0]):int(cord[0])+t,int(cord[1]):int(cord[1])+1]
                    #print("valores",Val)
                    Val=Val==0
                    #print("Booleano",Val)
                    if np.all(Val)==True:
                        print("Position is saved")
                        TabP2[int(cord[0]):int(cord[0])+t,int(cord[1]):int(cord[1])+1]=1
                        #print(TabP2)
                        TabT2[int(cord[0]):int(cord[0])+t,int(cord[1]):int(cord[1])+1]=1
                        print(TabT2[::])
                        break
                    else:
                        print("One or more positions are been used with other ship\nTry again")
    # HACIA LA IZQUIERDA OESTE
            elif d=="W":
                if int(cord[1]-t+1)<0: # izquierda
                    print("Will be out of board\nTry again")
                    print(TabT2[::])
                else:
                    Val=TabP2[int(cord[0]):int(cord[0])+1,int(cord[1])-t+1:int(cord[1])+1]
                    #print("valores",Val)
                    Val=Val==0
                    #print("Booleano",Val)
                    if np.all(Val)==True:
                        print("Position is saved")
                        TabP2[int(cord[0]):int(cord[0])+1,int(cord[1])-t+1:int(cord[1])+1]=1
                        #print(TabP2)
                        TabT2[int(cord[0]):int(cord[0])+1,int(cord[1])-t+1:int(cord[1])+1]=1
                        print(TabT2[::])
                        break
                    else:
                        print("One or more positions are been used with other ship\nTry again")
    # HACIA LA DERECHA ESTE
            elif d=="E":
                if int(cord[1]+t-1)>6: # Derecha
                    print("Will be out of board\nTry again")
                    print(TabT2[::])
                else:
                    Val=TabP2[int(cord[0]):int(cord[0])+1,int(cord[1]):int(cord[1])+t]
                    #print("valores",Val)
                    Val=Val==0
                    #print("Booleano",Val)
                    if np.all(Val)==True:
                        print("Position is saved")
                        TabP2[int(cord[0]):int(cord[0])+1,int(cord[1]):int(cord[1])+t]=1
                        #print(TabP2)
                        TabT2[int(cord[0]):int(cord[0])+1,int(cord[1]):int(cord[1])+t]=1
                        print(TabT2[::])
                        break
                    else:
                        print("One or more positions are been used with other ship\nTry again")
    # HACIA LA ARRIBA NORTE
            elif d=="N":
                if int(cord[0]-t+1)<0: # Arriba
                    print("Will be out of board\nTry again")
                    print(TabT2[::])
                else:
                    Val=TabP2[int(cord[0]-t+1):int(cord[0])+1,int(cord[1]):int(cord[1])+1]
                    #print("valores",Val)
                    Val=Val==0
                    #print("Booleano",Val)
                    if np.all(Val)==True:
                        print("Position is saved")        
                        TabP2[int(cord[0]-t+1):int(cord[0])+1,int(cord[1]):int(cord[1])+1]=1
                        #print(TabP2)
                        TabT2[int(cord[0]-t+1):int(cord[0])+1,int(cord[1]):int(cord[1])+1]=1
                        print(TabT2[::])
                        break
                    else:
                        print("One or more positions are been used with other ship\nTry again")
            else:
                print("Which direction want to extend your ship\nN: North(↑)\nS: South(↓)\nE: East(→)\nW: West(←)\n")

        except TypeError:
            print("Remeber to choose a number from the board\n#1 are positions you are using already\nTry again")
            print(TabT2[::])
        except ValueError:
            print("Letters and symbols are not allowed\n#1 are positions you are using already\nTry again")
            print(TabT2[::])
        except Exception as ex: # Si no puede, entonces haga, un "Exception" es cualquier error que salga
            print(f"An another error ocurred {type(ex)}{ex}")

print("------------//------------//------------")
print(f"{P2} los #1 son las posiciones de tus barcos\n{TabP2[::]}")

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]]

Tao, Please place your ship range 4th


KeyboardInterrupt: 

In [20]:
# Sección ataques
while True:
    # Turno del jugador 1
#    print("Player one, Your ships positions")
#    print(TabP1)
#    print("-------------//----------------")
    print(TabA1)
    a=input(f"{P1}, Select an attack position\n")
    a=int(a)
    if a in TabA1:
        if a in Eval1:
            print("Choose again")
        else:
            a=np.where(TabA1 == a)
            if TabP2[a]==1:
                print(f"!!BOOM!!, {P1} hitted {P2}\n")
                TabP2[a]=0
                TabA1[a]=1
                print(TabA1)
                # Evaluar ganador
                if np.any(TabP2)==1:
                    print(f"\n{P2} is your turn\n")
                else:
                    print(f"{P1}, you win")
                    print(f"{P1}\'s Final ships positions")
                    print(TabP1)
                    print(f"{P2}\'s Final ships positions")
                    print(TabP2)
                    break
            elif TabP2[a]==0:
                print("You missed")
                TabA1[a]=0
                print(TabA1)
    else:
        print("Try again with a number in the board")
    print("-------------//----------------")

    # Turno del jugador 2
#    print("Player two, Your ships positions")
#    print(TabP2)
#    print("-------------//----------------")
    print(TabA2)
    a=input(f"{P2}, Select an attack position\n")
    a=int(a)
    if a in TabA2:
        if a in Eval2:
            print("Choose again")
        else:
            a=np.where(TabA2 == a)
            if TabP1[a]==1:
                print(f"!!BOOM!!, {P2} hitted {P1}\n")
                TabP1[a]=0
                TabA2[a]=1
                print(TabA2)
                # Evaluar ganador
                if np.any(TabP1)==1:
                    print(f"\n{P1} is your turn\n")
                else:
                    print(f"{P2}, you win")
                    print(f"{P1}\'s Final ships positions")
                    print(TabP1)
                    print(f"{P2}\'s Final ships positions")
                    print(TabP2)
                    break
            elif TabP1[a]==0:
                print("You missed")
                TabA2[a]=0
                print(TabA2)
    print("-------------//----------------")
    print("-------------//----------------")

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
tao, Select an attack position
2
!!BOOM!!, tao hitted lilly

[[ 1  3  4]
 [ 5  6  7]
 [ 8  9 10]]

lilly is your turn

-------------//----------------
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
lilly, Select an attack position
2
!!BOOM!!, lilly hitted tao

[[ 1  3  4]
 [ 5  6  7]
 [ 8  9 10]]

tao is your turn

-------------//----------------
-------------//----------------
[[ 1  3  4]
 [ 5  6  7]
 [ 8  9 10]]
tao, Select an attack position
3
!!BOOM!!, tao hitted lilly

[[ 1  1  4]
 [ 5  6  7]
 [ 8  9 10]]

lilly is your turn

-------------//----------------
[[ 1  3  4]
 [ 5  6  7]
 [ 8  9 10]]
lilly, Select an attack position
3
!!BOOM!!, lilly hitted tao

[[ 1  1  4]
 [ 5  6  7]
 [ 8  9 10]]

tao is your turn

-------------//----------------
-------------//----------------
[[ 1  1  4]
 [ 5  6  7]
 [ 8  9 10]]
tao, Select an attack position
4
!!BOOM!!, tao hitted lilly

[[ 1  1  1]
 [ 5  6  7]
 [ 8  9 10]]

lilly is your turn

-------------//-------------

In [14]:
#Confirmación de ganador
print("Posición jugador 1")
print(TabP1)
print("Posición jugador 2")
print(TabP2)

Posición jugador 1
[[0 0 0]
 [0 0 0]
 [0 1 0]]
Posición jugador 2
[[0 0 0]
 [0 0 0]
 [0 0 0]]


# Posiscionar barcos del Jugador 2
print(TabA2[::])
TabT2=TabA2[:].copy()
for t in Bu:
    print(f"\n{P2}, Please place your ship range {t}th")
    while True:
        try:
            po=int(input("Wich Position will you want to place your ship\nRemember 0 an 1 are not avaiable: "))
            cord=np.where(TabA2==po)
            int(cord[0]) # Evaluar que la posición exista
            d=input("Which direction want to extend your ship\nN: North(↑)\nS: South(↓)\nE: East(→)\nW: West(←)\n").upper()
    # HACIA LA Abajo SUR
            if d=="S":
                if int(cord[0]+t-1)>6: # Hacia el Sur, Abajo
                    print("Will be out of board\nTry again")
                    print(TabT2[::])
                else:
                    Val=TabP2[int(cord[0]):int(cord[0])+t,int(cord[1]):int(cord[1])+1]
                    #print("valores",Val)
                    Val=Val==0
                    #print("Booleano",Val)
                    if np.all(Val)==True:
                        print("Position is saved")
                        TabP2[int(cord[0]):int(cord[0])+t,int(cord[1]):int(cord[1])+1]=1
                        #print(TabP2)
                        TabT2[int(cord[0]):int(cord[0])+t,int(cord[1]):int(cord[1])+1]=1
                        print(TabT2[::])
                        break
                    else:
                        print("One or more positions are been used with other ship\nTry again")
    # HACIA LA IZQUIERDA OESTE
            elif d=="W":
                if int(cord[1]-t+1)<0: # izquierda
                    print("Will be out of board\nTry again")
                    print(TabT2[::])
                else:
                    Val=TabP2[int(cord[0]):int(cord[0])+1,int(cord[1])-t+1:int(cord[1])+1]
                    #print("valores",Val)
                    Val=Val==0
                    #print("Booleano",Val)
                    if np.all(Val)==True:
                        print("Position is saved")
                        TabP2[int(cord[0]):int(cord[0])+1,int(cord[1])-t+1:int(cord[1])+1]=1
                        #print(TabP2)
                        TabT2[int(cord[0]):int(cord[0])+1,int(cord[1])-t+1:int(cord[1])+1]=1
                        print(TabT2[::])
                        break
                    else:
                        print("One or more positions are been used with other ship\nTry again")
    # HACIA LA DERECHA ESTE
            elif d=="E":
                if int(cord[1]+t-1)>6: # Derecha
                    print("Will be out of board\nTry again")
                    print(TabT2[::])
                else:
                    Val=TabP2[int(cord[0]):int(cord[0])+1,int(cord[1]):int(cord[1])+t]
                    #print("valores",Val)
                    Val=Val==0
                    #print("Booleano",Val)
                    if np.all(Val)==True:
                        print("Position is saved")
                        TabP2[int(cord[0]):int(cord[0])+1,int(cord[1]):int(cord[1])+t]=1
                        #print(TabP2)
                        TabT2[int(cord[0]):int(cord[0])+1,int(cord[1]):int(cord[1])+t]=1
                        print(TabT2[::])
                        break
                    else:
                        print("One or more positions are been used with other ship\nTry again")
    # HACIA LA ARRIBA NORTE
            elif d=="N":
                if int(cord[0]-t+1)<0: # Arriba
                    print("Will be out of board\nTry again")
                    print(TabT2[::])
                else:
                    Val=TabP2[int(cord[0]-t+1):int(cord[0])+1,int(cord[1]):int(cord[1])+1]
                    #print("valores",Val)
                    Val=Val==0
                    #print("Booleano",Val)
                    if np.all(Val)==True:
                        print("Position is saved")        
                        TabP2[int(cord[0]-t+1):int(cord[0])+1,int(cord[1]):int(cord[1])+1]=1
                        #print(TabP2)
                        TabT2[int(cord[0]-t+1):int(cord[0])+1,int(cord[1]):int(cord[1])+1]=1
                        print(TabT2[::])
                        break
                    else:
                        print("One or more positions are been used with other ship\nTry again")
            else:
                print("Which direction want to extend your ship\nN: North(↑)\nS: South(↓)\nE: East(→)\nW: West(←)\n")

        except TypeError:
            print("Remeber to choose a number from the board\n#1 are positions you are using already\nTry again")
            print(TabT2[::])
        except ValueError:
            print("Letters and symbols are not allowed\n#1 are positions you are using already\nTry again")
            print(TabT2[::])
        except Exception as ex: # Si no puede, entonces haga, un "Exception" es cualquier error que salga
            print(f"An another error ocurred {type(ex)}{ex}")

print("------------//------------//------------")
print(f"{P2} los #1 son las posiciones de tus barcos\n{TabP2[::]}")

# Evaluar ganador
print(TabP1)
if np.any(TabP1)==1:
    print("Siguiente")
else:
    print("Ganaste")
print("-------------//----------------")
TabP1[:,2]=0
TabP1

# Ubicación de barcos reemplazando arreglo de una dimensión
"""
Pru=np.arange(2,7*7+2,1)
Pru=Pru.reshape((7,7))
Pru
print("-------------//----------------")
Pru=Pru.reshape((1,7*7))
Pru
print("-------------//----------------")
n=8 # Posición 8
p="w" # Dirección West
r=4 # Ship Range
#Toca abarcar 5 al 8 equivale a posición 6 al 3
#np.where(Pru==8)
Pru[0,n-r-1]=1
Pru[0,n-r]=1
Pru[0,n-r+1]=1
Pru[0,n-r+2]=1
#Pru[[n-r+2,n-r+1,n-r,n-r-1]] = 1
print(Pru)
print("-------------//----------------")
Pru=Pru.reshape((7,7))
Pru
"""